defaults:
  agent: vanilla_policy_gradients
  robot: point
  log_dir: results
  seed: 0
  time_limit: 1000
  epochs: 200
  eval_every: 10
  eval_trials: 5
  train_driver: {adaptation_steps: 5000, query_steps: 2000}
  test_driver: {adaptation_steps: 5000, query_steps: 2000}
  action_repeat: 2
  render_episodes: 1
  render_options: {height: 320, width: 320, camera_id: 'fixedfar'}
  jit: True
  precision: 32

no_adaptation:
  task: go_to_goal
  train_driver: {adaptation_steps: 30000, query_steps: 0}
  test_driver: {adaptation_steps: 1000, query_steps: 0}
  eval_trials: 10


vanilla_policy_gradients:
  entropy_regularization: 0.
  update_steps: 80
  actor: {layers: [256, 256], min_stddev: 1e-5, max_stddev: 10., activation: jnn.relu, initialization: glorot}
  critic: {layers: [256, 256], dist: normal, activation: jnn.relu, name: 'critic', initialization: glorot}
  discount: 0.99
  safety_discount: 0.95
  lambda_: 0.97
  num_trajectories: 30
  actor_opt: {lr: 3e-4, eps: 1e-7, clip: 10}
  critic_opt: {lr: 1e-3, eps: 1e-7, clip: 10}
