defaults:
  log_dir: results
  seed: 0
  time_limit: 1000
  epochs: 200
  train_driver: {adaptation_steps: 5000, query_steps: 2000, iters: 10}
  test_driver: {adaptation_steps: 5000, query_steps: 2000, iters: 5}
  action_repeat: 2
  render_episodes: 0
  render_options: {}
  initialization: glorot
  jit: True
  precision: 32
  discount: 0.99
  safety_discount: 0.95
  lambda_: 0.95


vanilla_policy_gradients:
  entropy_regularization: 0.
  update_steps: 80
